name: Publish
on:
    push:
        branches:
            - master
            - main
    schedule:
        - cron: "0 12 * * *"
    workflow_dispatch:
jobs:
    publish-site:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.12.1"
            - name: Install
              run: npm ci
            - name: Rebuild docs
              run: |
                  git clone https://github.com/prosopo/captcha.git
                  cd captcha
                  git checkout $(git describe --tags --abbrev=0)
                  npm ci
                  npm run build:all
                  npx typedoc --options ../typedoc.json --gitRevision $(git describe --tags --abbrev=0) --sitemapBaseUrl "https://docs.prosopo.io/"
                  cd ..
#            - name: Rebuild /example
#              run: |
#                  cd captcha/example
#                  npm ci
#                  node ../bin/typedoc --options ../../example.typedoc.json --gitRevision $(git describe --tags --abbrev=0) --sitemapBaseUrl "https://docs.prosopo.io/"
#                  cd ../..
#            - name: Rebuild schema.json
#              run: |
#                  cd captcha
#                  node scripts/generate_options_schema.js ../_site/schema.json
#                  cd ..
            - name: Rebuild markdown site
              run: npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: _site
                  git-config-name: TypeDoc Bot
                  git-config-email: typedoc@gerritbirkeland.com
                  single-commit: true
